### ISSUE TITLE
hard coded i18n dependancy

### ISSUE THREAD

**Issue by jswhisperer** [Appclon/ignite-appclon-mobx#1]
There is a hard coded i18n dependancy. So if you select 'no' from the CLI you can't start the app until manually removing all the calls to i18n

**Comment by jswhisperer** [comment]
Also hard coded react-native-animatable

**Comment by paomosca** [comment]
thanks for testing, this module is a direct derivation of an old version of ignite boilerplate, where probably modules were hard coded. i'll try to update it as soon as possible. feel free to contribute if you can!

**Comment by jswhisperer** [comment]
I've jumped onto another boilerplate in the mean time, but looks like a lot of potential with yours! Just wanted to give you the heads up :)
